[book]
authors = ["Mohan Gupta"]
language = "en"
multilingual = false
src = "src"
title = "Useful Tools Notebook"

[output.html]
git-repository-url = "https://github.com/mohankumargupta/mdbook-example"